/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import ModelosAux.Tiempo;
import javax.swing.JOptionPane;
import modelos.Auto;
import org.jdesktop.application.Action;
import sockets.ClienteMonitor;

/**
 *
 * @author oscar
 */
public class FrmCobroOficina extends javax.swing.JDialog {
    private Auto auto;
    ClienteMonitor clienteMonitor;
    public FrmCobroOficina(java.awt.Frame parent, boolean modal,Auto auto,ClienteMonitor clienteMonitor) {
        super(parent,"Cobro oficina", modal);
        initComponents();
        this.auto = auto;
        this.clienteMonitor =  clienteMonitor;
        this.txtFechaEntrada.setText(auto.getFechaEntrada());
        this.txtHoraEntrada.setText(auto.getHoraEntrada());
        this.txtFechaSalida.setText(Tiempo.getFecha());
        this.txtHoraSalida.setText(Tiempo.getHora());
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFechaEntrada = new javax.swing.JTextField();
        txtHoraEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        txtHoraSalida = new javax.swing.JTextField();
        btnCobrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Entrada");
        jLabel1.setName("jLabel1"); // NOI18N

        txtFechaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaEntrada.setName("txtFechaEntrada"); // NOI18N

        txtHoraEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraEntrada.setName("txtHoraEntrada"); // NOI18N

        jLabel2.setText("Salida");
        jLabel2.setName("jLabel2"); // NOI18N

        txtFechaSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaSalida.setName("txtFechaSalida"); // NOI18N

        txtHoraSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraSalida.setName("txtHoraSalida"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(FrmCobroOficina.class, this);
        btnCobrar.setAction(actionMap.get("onCobrar")); // NOI18N
        btnCobrar.setText("Cobrar");
        btnCobrar.setName("btnCobrar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCobrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
     private boolean validaCamposEntrada() {

        if (txtFechaEntrada.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Introduce la nueva fecha de entrada.",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtFechaEntrada.grabFocus();
            return false;
        }
        if (!this.txtFechaEntrada.getText().matches("[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]")){
            JOptionPane.showMessageDialog(this,"La fecha de entrada debe de terner formato 0000-00-00",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtFechaEntrada.grabFocus();
            return false;
        }
        
        if (txtFechaSalida.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Introduce la nueva fecha de dalida.",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtFechaSalida.grabFocus();
            return false;
        }
        if (!this.txtFechaSalida.getText().matches("[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]")){
            JOptionPane.showMessageDialog(this,"La fecha de salida debe de terner formato 0000-00-00 ",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtFechaSalida.grabFocus();
            return false;
        }

        
        
        if (txtHoraEntrada.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Introduce la nueva hora de entrada.",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtHoraEntrada.grabFocus();
            return false;
        }
        if (!this.txtHoraEntrada.getText().matches("[0-9][0-9]:[0-9][0-9]")){
            JOptionPane.showMessageDialog(this,"La hora de entrada debe de tener formato 00:00 ",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtHoraEntrada.grabFocus();
            return false;
        }
       
         
        if (txtHoraSalida.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Introduce la nueva hora de salida.",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtHoraSalida.grabFocus();
            return false;
        }
        if (!this.txtHoraSalida.getText().matches("[0-9][0-9]:[0-9][0-9]")){
            JOptionPane.showMessageDialog(this,"La hora de salida debe de terner formato 00:00 ",
            "Formato erroneo",JOptionPane.WARNING_MESSAGE);
            txtHoraSalida.grabFocus();
            return false;
        }
        

        return true;
     }
    
    @Action
    public void onCobrar() {
        if(this.validaCamposEntrada()){
            auto.setIsBoletoOficina(true);
            //auto.setIsBoletoManual(true);
            auto.setHoraEntrada(txtHoraEntrada.getText());
            auto.setFechaEntrada(txtFechaEntrada.getText());
            auto.setHoraSalida(txtHoraSalida.getText());
            auto.setFechaSalida(txtFechaSalida.getText());
            clienteMonitor.actualizarAuto(auto);
            JOptionPane.showMessageDialog(this, "El boleto se cerro correctamente");
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtHoraEntrada;
    private javax.swing.JTextField txtHoraSalida;
    // End of variables declaration//GEN-END:variables
}
