

package vistas;

import modelos.Estacionamiento;
import modelos.Progresivo;
import modelos.Turno;

/**
 *
 * @author sistema
 */
public class FrmFolios extends javax.swing.JDialog {
    Estacionamiento estacionamiento;
    Turno turno;
    /** 
     * Creates new form FrmFolios
     */
    public FrmFolios(java.awt.Frame parent, boolean modal,Turno turno,Estacionamiento estacionamiento) {
        super(parent, modal);
        initComponents();
        this.turno = turno;
        this.estacionamiento = estacionamiento;
         String ser = "";
        for(String s : estacionamiento.getCaseta().getSeries())
            ser+=s+" ";
        txtBoleto.setText(Progresivo.getUltimoProgresivo(estacionamiento.getCaseta(), "BOLETO"));
        txtRetiro.setText(Progresivo.getUltimoProgresivo(estacionamiento.getCaseta(), "RETIRO_PARCIAL"));
        txtPerdido.setText(Progresivo.getUltimoProgresivo(estacionamiento.getCaseta(), "PERDIDO"));
        txtRecibo.setText(Progresivo.getUltimoProgresivo(estacionamiento.getCaseta(), "RECIBO_PAGO"));
        btnGuardar.setVisible(false);
        txtSeries.setText(ser);
        if(estacionamiento.getTipo().equals("Valet")){
            jLabel6.setVisible(false);
            txtSeries.setText("0");
            txtSeries.setVisible(false);
            
        }
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBoleto = new javax.swing.JTextField();
        txtPerdido = new javax.swing.JTextField();
        txtRetiro = new javax.swing.JTextField();
        txtRecibo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSeries = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel1.setText("Boletos");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 134, -1));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel2.setText("Boletos perdido");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 134, -1));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Recibo pago");
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 134, -1));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel4.setText("Retiro parcial");
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 134, 15));

        txtBoleto.setEditable(false);
        txtBoleto.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtBoleto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBoleto.setName("txtBoleto"); // NOI18N
        getContentPane().add(txtBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, -1));

        txtPerdido.setEditable(false);
        txtPerdido.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtPerdido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPerdido.setName("txtPerdido"); // NOI18N
        getContentPane().add(txtPerdido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));

        txtRetiro.setEditable(false);
        txtRetiro.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtRetiro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRetiro.setName("txtRetiro"); // NOI18N
        getContentPane().add(txtRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, -1));

        txtRecibo.setEditable(false);
        txtRecibo.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtRecibo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRecibo.setName("txtRecibo"); // NOI18N
        getContentPane().add(txtRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 310, 40));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        btnEditar.setText("Modificar");
        btnEditar.setName("btnEditar"); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 310, 40));

        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 50, 10));

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel6.setText("Series");
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 134, -1));

        txtSeries.setEditable(false);
        txtSeries.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtSeries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeries.setName("txtSeries"); // NOI18N
        getContentPane().add(txtSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtBoleto.setEditable(true);
        txtRetiro.setEditable(true);
        txtPerdido.setEditable(true);
        txtRecibo.setEditable(true);
        txtSeries.setEditable(true);
        btnEditar.setVisible(false);
        btnGuardar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Progresivo.setProgresivo(estacionamiento.getCaseta(), "BOLETO",Integer.valueOf(txtBoleto.getText()));
        Progresivo.setProgresivo(estacionamiento.getCaseta(), "RETIRO_PARCIAL",Integer.valueOf(txtRetiro.getText()));
        Progresivo.setProgresivo(estacionamiento.getCaseta(), "PERDIDO",Integer.valueOf(txtPerdido.getText()));
        Progresivo.setProgresivo(estacionamiento.getCaseta(), "RECIBO_PAGO",Integer.valueOf(txtRecibo.getText()));
        estacionamiento.getCaseta().setSeries(txtSeries.getText().split(" "));
        estacionamiento.getCaseta().actualizar();
        txtBoleto.setEditable(false);
        txtRetiro.setEditable(false);
        txtPerdido.setEditable(false);
        txtRecibo.setEditable(false);
        txtSeries.setEditable(false);
        btnEditar.setVisible(true);
        btnGuardar.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtBoleto;
    private javax.swing.JTextField txtPerdido;
    private javax.swing.JTextField txtRecibo;
    private javax.swing.JTextField txtRetiro;
    private javax.swing.JTextField txtSeries;
    // End of variables declaration//GEN-END:variables
}
